//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.24 at 10:28:45 AM CEST 
//


package it.polito.dp2.RNS.sol3.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="self" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="suggestedPath" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="position" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="comesFrom" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="isDirectedTo" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="VehType" use="required" type="{}vehicleType" />
 *       &lt;attribute name="VehicleState" use="required" type="{}vehicleStateType" />
 *       &lt;attribute name="entryTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "self",
    "suggestedPath"
})
@XmlRootElement(name = "vehicle")
public class Vehicle {

    @XmlSchemaType(name = "anyURI")
    protected String self;
    @XmlSchemaType(name = "anyURI")
    protected String suggestedPath;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "position", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String position;
    @XmlAttribute(name = "comesFrom", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String comesFrom;
    @XmlAttribute(name = "isDirectedTo", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String isDirectedTo;
    @XmlAttribute(name = "VehType", required = true)
    protected VehicleType vehType;
    @XmlAttribute(name = "VehicleState", required = true)
    protected VehicleStateType vehicleState;
    @XmlAttribute(name = "entryTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar entryTime;

    /**
     * Gets the value of the self property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelf() {
        return self;
    }

    /**
     * Sets the value of the self property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelf(String value) {
        this.self = value;
    }

    /**
     * Gets the value of the suggestedPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuggestedPath() {
        return suggestedPath;
    }

    /**
     * Sets the value of the suggestedPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuggestedPath(String value) {
        this.suggestedPath = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the comesFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComesFrom() {
        return comesFrom;
    }

    /**
     * Sets the value of the comesFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComesFrom(String value) {
        this.comesFrom = value;
    }

    /**
     * Gets the value of the isDirectedTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDirectedTo() {
        return isDirectedTo;
    }

    /**
     * Sets the value of the isDirectedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDirectedTo(String value) {
        this.isDirectedTo = value;
    }

    /**
     * Gets the value of the vehType property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleType }
     *     
     */
    public VehicleType getVehType() {
        return vehType;
    }

    /**
     * Sets the value of the vehType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleType }
     *     
     */
    public void setVehType(VehicleType value) {
        this.vehType = value;
    }

    /**
     * Gets the value of the vehicleState property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleStateType }
     *     
     */
    public VehicleStateType getVehicleState() {
        return vehicleState;
    }

    /**
     * Sets the value of the vehicleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleStateType }
     *     
     */
    public void setVehicleState(VehicleStateType value) {
        this.vehicleState = value;
    }

    /**
     * Gets the value of the entryTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntryTime() {
        return entryTime;
    }

    /**
     * Sets the value of the entryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntryTime(XMLGregorianCalendar value) {
        this.entryTime = value;
    }

}
